name: Daily Raw Data Collection

on:
  schedule:
    # UTC 00:00 = Beijing 08:00
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动点按钮触发

jobs:
  collect_and_mail:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          pip install biopython
          
      - name: Run Collector Script
        env:
          # 不需要 GOOGLE_API_KEY
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python collect_raw.py
